# version: '3.3'

services:
  frontend:
    restart: always
    image: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "6002:3000"
    links:
      - backend:backend
    environment:
      - UPLOADTHING_SECRET=sk_live_4924629a1dd8c5a831fb9a91147671aff28fd8b25d96aefc2e914fddf64e1529
      - UPLOADTHING_APP_ID=ppfoqsvpwu
      - NEXTAUTH_URL=http://localhost:6002
      - NEXTAUTH_SECRET=Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY=
      - BACKEND_URL=http://backend:4000

  backend:
    restart: always
    image: backend
    build: ./backend
    expose:
      - "4000"
    ports:
      - "6001:4000"